Homework 02
DmytroTy/MA-NodeJS pull request #2
Opened 2020-11-11 15:15 UTC by DmytroTy

Пункти 1-10

2020-11-11 16:33 UTC, DmytroTy commented
Перероблено на пункт 11

2020-11-12 19:07 UTC, VitaliiHurin requested changes
Загалом дуже добре. 👍
Є кілька питань/зауважень:
- Не робив перемикання джерела? Щоб було як по завданню: або файлу, або зі змінної.
- Ще треба додати більше перевірок на помилки (огорнути в try/catch, де необхідно), бо робота з файловою системою та методами роботи з JSON можуть генерувати ексепшени. Треба це коректно оброблювати і повертати у відповідь на запит з відповідним кодом.

2020-11-12 19:07 UTC, VitaliiHurin commented on src/router.js
> +  if (method === 'POST' && url === '/new-data') return newData(data, response);
Тут мабуть краще переробити під switch/case

2020-11-12 19:07 UTC, VitaliiHurin commented on src/controller.js
> +}
Є сенс тут переробити task2 з експорту виклику на експорт функції.

2020-11-12 19:07 UTC, VitaliiHurin commented on SANDBOX.http
> +GET http://localhost:3000/
А є обробка кореня?

2020-11-12 19:07 UTC, VitaliiHurin commented on src/controller.js
> +function good(response, queryParams) {
Додай ще тут, будь ласка, базову перевірку queryParams

2020-11-12 19:07 UTC, VitaliiHurin commented on src/controller.js
> +  fs.writeFileSync(pathToFile, JSON.stringify(data, null, 1));
Тут також треба перевірку даних, що приходять на вхід.

2020-11-12 19:07 UTC, VitaliiHurin commented on SANDBOX.http
> +]
Краще зразу дані у валідному форматі тут вказати як приклад.

2020-11-13 05:18 UTC, DmytroTy commented
>     * Не робив перемикання джерела? Щоб було як по завданню: або файлу, або зі змінної.

2 коміти назад було перемикання по пункту 10. Переробити його було не важко на пункт 11 і зрозуміло (та й за умовою) не сумісне видалив.

2020-11-13 05:28 UTC, DmytroTy commented on SANDBOX.http
> +GET http://localhost:3000/
Обробка всіх не прописаних в роутері, й цього включно, повертає помилку 404.

2020-11-13 05:44 UTC, DmytroTy commented on src/router.js
> +  if (method === 'POST' && url === '/new-data') return newData(data, response);
Тільки 2 умови повністю однотипні й добре об'єднаються, а 2 інші так і вимагатимуть окремої перевірки, тому в цьому сенсу так і не бачу.

2020-11-13 09:58 UTC, DmytroTy commented on src/controller.js
> +}
Так це більш логічно, але в першому завданні було чітко сформульовано, тому сам від себе не став завдання переробляти.
А тепер переробив.

2020-11-13 10:13 UTC, DmytroTy commented
Всі перевірки на помилки й вхідних даних по вигляду зразкового масиву додав. JSON.stringify надіюсь не потрібно огортати в try/catch? (валідний об'єкт по ідеї без проблем має конвертуватись в рядок.)
Ще по одному питанню й зауваженню залишилось відкритими.

2020-11-13 19:09 UTC, VitaliiHurin commented
> 2 коміти назад було перемикання по пункту 10. Переробити його було не важко на пункт 11 і зрозуміло (та й за умовою завдання) не сумісне видалив.
> Хоча по ідеї можна його й поєднати, але зробивши трохи не так як було.

Ок, добре.

2020-11-13 19:17 UTC, VitaliiHurin commented
> JSON.stringify надіюсь не потрібно огортати в try/catch? (валідний об'єкт по ідеї без проблем має конвертуватись в рядок.)
По хорошому то треба все-таки і його обертати, бо і він викидує exception'и...
Хоча тут є обробка uncaughtException, так що ок. Зараховую. 🙂👍

2020-11-13 19:17 UTC, VitaliiHurin approved these changes

2020-11-13 19:18 UTC, merged

2020-11-13 19:19 UTC, VitaliiHurin commented on src/router.js
> +  if (method === 'POST' && url === '/new-data') return newData(data, response);
Добре.

2020-11-13 19:19 UTC, VitaliiHurin commented on SANDBOX.http
> +GET http://localhost:3000/
Ок.