Homework 03
DmytroTy/MA-NodeJS pull request #4
Opened 2020-11-17 07:31 UTC by DmytroTy

"Ялинки" готові.
Через перевиклик велику кількість разів, та ще й не визначену наперед, "ялинки" принципово не можливо розкласти в "ланцюжок".
Цикл for з асинхронними функціями не може працювати.

2020-11-17 21:41 UTC, VitaliiHurin requested changes
Все класно. Із суттєвого тільки треба переробити "ялинку" від `getDiscountPromise()` на роботу з промісами. 🙂👍
І ще очікується повертати не скореговану ціну, а товар з додатковим полем "знижка" у відсотках.

2020-11-17 21:41 UTC, VitaliiHurin commented on src/controller.js
> +}
Оце все можна краще винести десь окремо, щоб не в контроллерах лежало.

2020-11-17 21:41 UTC, VitaliiHurin commented on src/controller.js
> +    });
Тут можна було заморочитись глибше, набираючи знижки в масив і крутити рекурсивно, поки кількість знижок не досягне необхідної для певної групи товарів. Але і так підходить як більше зрозуміле і прямолінійне рішення. 🙂

2020-11-17 21:41 UTC, VitaliiHurin commented on src/controller.js
> +    });
Щось тут виходить теж на колбеках, хоч має бути на промісах. Тут така сама б "ялинка" була, тільки все через `.then()`

2020-11-17 21:41 UTC, VitaliiHurin commented on src/router.js
>    if (method === 'GET' && url === '/standardize') return standardize(response);
Зроби краще мабуть все-таки один `if (method === 'GET')` і далі в середині перевірка url'ів через switch/case.

2020-11-17 22:41 UTC, DmytroTy commented on src/controller.js
> +    });
Це справді було б хорошим рішенням, але я про таке не подумав.

2020-11-17 22:52 UTC, DmytroTy commented on src/controller.js
> +    });
> Із суттєвого тільки треба переробити "ялинку" від `getDiscountPromise()` на роботу з промісами. slightly_smiling_face+1

Рекурсія function getDiscountPromise(callback) реалізована як слід виключно на промісах, доки не поверне бажаний результат в callback. На цьому вона власне й закінчується і там все добре.

В принципі є тільки 2 варіанти обробки: колбеками (хоча й 2 виглядів, але однак звичайні колбеки повертають дані) або за допомогою синтаксичного сахару нібито синхронно.

Саме в цьому місці як написав з самого початку ялинку не можна розкласти в ланцюжок. Намагався розкласти .then() як прийнято, але саме в цьому місці принципово не  можливо! Це фактично єдиний вигляд того позитивного callback, який всередині .then() потім опрацьовує вже отримані результати.

Про те щоб спочатку зібрати знижки в масив і потім легко разом обробити не подумав. Але тут навіть скоріше щоб модернізувати на повернення з рекурсії необхідної кількості знижок більше однієї за раз.

2020-11-18 08:11 UTC, DmytroTy commented on src/controller.js
> +    });
> Щось тут виходить теж на колбеках, хоч має бути на промісах. Тут така сама б "ялинка" була, тільки все через `.then()`

Так це такий вигляд того колбека, що в `.then()` остаточно опрацьовує дані.

Конкретніше проблема в тому, що на 1 позитивний результат сиплеться 5 помилок і таке значне та ще й випадкове зміщення по ланцюжку все ламає. Наскільки бачу проміси працюють тільки з однією чи кількома помилками з передбаченням дій під кожну конкретно. В нас тут вже від першого виклику сиплеться 5 +/- 5 помилок і це вже непередбачувано, а всього їх сотні. Про такий довгий ланцюжок можна і не мріяти. Тому тільки рекурсія по кожному окремому випадку.


Для часткової реабілітації промісів зробив запропоновану вище модернізацію.

2020-11-18 08:36 UTC, DmytroTy commented on src/controller.js
> +}
require виявляється сповільнюють виконання функцій з інших файлів.

2020-11-18 09:50 UTC, DmytroTy commented on src/router.js
>    if (method === 'GET' && url === '/standardize') return standardize(response);
Згадав як можна всі if (method === 'GET') об'єднати.

2020-11-20 10:19 UTC, DmytroTy commented
З промісами пояснив достатньо зрозуміло ситуацію чи ні?

Їх колбек спростив наскільки було можливо, використавши запропоновану ідею.

Є додаткові зауваження?

2020-11-20 14:24 UTC, VitaliiHurin requested changes
> З промісами пояснив достатньо зрозуміло ситуацію чи ні?
Так.

> Є додаткові зауваження?
try/catch для всіх async функцій треба.

2020-11-20 14:24 UTC, VitaliiHurin commented on src/controller.js
>      return product;
Хороша практика всюди, де async функція робити try/catch блок всередині, це полегшує сильно дебаг, коли щось ламається.

2020-11-22 05:17 UTC, DmytroTy commented on src/controller.js
> +    });
Так і зробив з допомогою масиву й тут, раз так вважається красивіше.

2020-11-22 05:34 UTC, DmytroTy commented
Додав try/catch
Додав функції myMap і myMapAsync до Array.prototype як було в додатковій частині завдання.
В алгоритмі обробки з промісами знайшов помилку, виправив, так навіть простіше вийшло.
Вирішив таки переробити колбеки на меншу вкладеність.

2020-11-22 20:05 UTC, merged