Homework 04
DmytroTy/MA-NodeJS pull request #5
Opened 2020-11-25 16:11 UTC by DmytroTy

Пункти 1-4.

2020-11-29 12:47 UTC, VitaliiHurin reviewed
Треба додати перевірку на відсутність папки (і якщо треба, то створити її), бо зараз падає помилка, хоч отримую 200 у відповідь.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/12820903/100542286-8df02f00-3251-11eb-9302-c7478844a775.png">

2020-11-29 12:47 UTC, VitaliiHurin commented on src/server/controller.js
> +  const filePath = `./upload/${timestamp}_${id}.json`;
Щоб не прописувати хардкодом в декількох місцях папку, краще її винести в env var і в побудові шляху використати модуль path.

2020-11-29 12:47 UTC, VitaliiHurin commented on src/server/controller.js
> +  fs.readdir('./upload', (err, files) => {
Краще винести папку в env var.

2020-11-29 12:47 UTC, VitaliiHurin commented on src/server/controller.js
> +  const fileName = url.slice(url.lastIndexOf('/') + 1);
Тут теж можна використати модуль path.

2020-11-29 12:47 UTC, VitaliiHurin commented on src/server/service.js
> +  let filePath = path.resolve('./upload/optimized/', fileName);
Тут так само.

2020-11-29 12:47 UTC, VitaliiHurin commented on src/server/service.js
> +    filePath = path.resolve('./upload/', fileName);
І тут.

2020-11-29 14:09 UTC, DmytroTy commented on src/server/controller.js
> +  const fileName = url.slice(url.lastIndexOf('/') + 1);
А тут не зрозуміло, бо просто вирізаю ім'я файлу з рядка url запиту.

2020-11-29 14:10 UTC, DmytroTy commented
> Ще у мене така помилка вилазить:

Так fs.rm функція з модуля Ноди, з нею в мене ніколи проблем не було.

> Як я розумію, сьомого пункту завдання тут нема, так? slightly_smiling_faceЛише 1-4?

Саме дописував останні частини завдання 7-го пункту. Зараз він вже повністю завершений.

2020-11-29 15:32 UTC, DmytroTy commented
> Треба додати перевірку на відсутність папки (і якщо треба, то створити її), бо зараз падає помилка, хоч отримую 200 у відповідь.

Додав і створення папки й прокидування помилки нагору.

2020-12-01 06:20 UTC, DmytroTy commented on src/server/controller.js
> +  const fileName = url.slice(url.lastIndexOf('/') + 1);
Так, є перевага в path, використав його.

2020-12-01 18:53 UTC, VitaliiHurin commented
Коли роблю /stores-csv/optimize/1.json (неправильне ім'я файлу), то отримую код 202, а в консоль падає ексепшн. Треба додати перевірку на наявність файлу і відразу відповідати клієнту коректною помилкою, якщо файла не знаходить.

2020-12-01 19:03 UTC, VitaliiHurin requested changes
Додай, будь ласка, цю одну перевірку. Все інше - ок.

2020-12-02 07:06 UTC, DmytroTy commented
Додав. 
Як я міг забути тут за базову перевірку вхідних даних, дякую що нагадали.

2020-12-02 14:23 UTC, VitaliiHurin commented on src/server/controller.js
> +    csvOptimization(fileName);
Я б це виніс з-під try/catch'a на 404, бо якщо щось впаде в csvOptimization, то це вже 500 помилку треба відправляти... 🙂
Тобто для 404 тільки перевірка файлу щоб була.

2020-12-02 14:25 UTC, VitaliiHurin approved these changes

2020-12-02 14:38 UTC, DmytroTy commented on src/server/controller.js
> +    csvOptimization(fileName);
Тут однаково, бо виконується вже після того як респоз відправлений і щоб не сталось, а відправка нічого більше й не передбачена поки що, от як її б зробити... тоді б інша розмова була.

2020-12-02 22:11 UTC, merged